---

include: 'https://raw.githubusercontent.com/riboseinc/rpm-specs/master/ci.template.yml'

test:
  stage: test
  script: |
    yum -y -q localinstall RPMS/x86_64/{botan2-2*,botan2-devel*}.rpm
    # build our C++ test
    yum -y -q install gcc-c++
    g++ -std=c++11 $(pkg-config --cflags --libs botan-2) tests/test.cpp -otests/test
    # make sure we actually linked against the botan-2 shared obj
    ldd ./tests/test | grep botan-2
    # test that we can run our program without the devel package installed
    yum -y -q remove botan2-devel
    ./tests/test
    # test the python package
    yum -y -q install epel-release
    yum -y -q localinstall RPMS/x86_64/python34-botan2*.rpm
    ./tests/test.py

